### ISSUE TITLE
Familiarize yourself with new lab template

### ISSUE THREAD

**Issue by ShiqiYang2022** [gentzkow/GentzkowLabTemplate#15]
The goal of this issue is for @lucamlouzada @linxicindyzeng to familiarize themselves with the new lab template. All of our lab's new projects will use the new `GentzkowLabTemplate`, though we are continuing using our [archived template](https://github.com/gentzkow/template_archive) for existing projects.

Specifically, I would like both of you complete the following steps:

- [ ] Look over the [documentation](https://github.com/gentzkow/GentzkowLabTemplate/wiki)
- [ ] Try running the template "out of the box". 
- [ ] Try copying over and running the Python / Stata / R / Latex example scripts following the instructions [here](https://github.com/gentzkow/GentzkowLabTemplate/wiki#examples).
- [ ] Initialize a separate branch named `issue15-test-yourname` and push the results from each of the steps to that branch.
- [ ] Identify and report any place in the template or wiki that make you confused and a proposal to resolve, if any. Feel free to skip this if you can confirm everything goes smoothly.
- [ ] After finishing all of above, post a stable link for your test branch and tag @ShiqiYang2022 to review.

I think @lucamlouzada has not get the push access to this template yet, so you can prioritize your other onboarding tasks for now. Matt will grant your access soon.

Thanks all for your work!

**Comment by linxicindyzeng** [comment]
@ShiqiYang2022 Thanks! Will do this after I finish the initial onboarding in the DChan Lab :D

**Comment by lucamlouzada** [comment]
Sounds good, thanks! I'll start by completing the practice tasks with the archived template - first on my personal PC and again on the work Macbook when I get it next week. I'll then look over the new template.

**Comment by ShiqiYang2022** [comment]
@lucamlouzada Thanks! This is very clear, and the suggestions are great and super helpful.

For your specific comments, I agree with all. Would it be convenient for you to open a branch linked to this issue and address those accordingly? We will bring those fixes back to `master`. For Git-lfs item, I think this item is also in our to-do list [here](https://github.com/gentzkow/GentzkowLabTemplate/blob/ee79b88c3c0b4f75001863d49ddcd0124d591b1b/issue/nextstep.lyx#L284). Maybe we can try to combine the fix with having this context in mind.

For General suggestions, those all make sense to me. We will discuss more in our meeting. If you look at my [lyx draft](https://github.com/gentzkow/GentzkowLabTemplate/blob/ee79b88c3c0b4f75001863d49ddcd0124d591b1b/issue/nextstep.lyx) which pulls all the to-dos, you can find that the 1st bullet related to (M), 2nd and 3rd related to (A), 4th related to (C). Please feel free to add those as your comment into the lyx file (in the "Notes" part) and push to related branch [`16-plan-supervise`](https://github.com/gentzkow/GentzkowLabTemplate/tree/16-plan-supervise) so we pull thoughts together for the meeting!

**Comment by ShiqiYang2022** [comment]
@lucamlouzada Thanks so much! The changes all looks great to me. 

For PR, I suggest we can hold up merging for a bit and wait for @linxicindyzeng to familiarize herself with new template. Let me know if you view a different way, thanks!

**Comment by linxicindyzeng** [comment]
1. On the Git LFS problem Luca mentions [here](https://github.com/gentzkow/GentzkowLabTemplate/issues/15#:~:text=Clicking%20on%20%22Use,using%20Git%20LFS.%E2%80%9D), storing all files using regular git is one solution but not the only one, especially if we prefer to keep open the option to exploit advantages of LFS.

    **How Git LFS in templates works in my understanding:**

    When someone uses our template to create a new repository, it clones all files, including any Git LFS pointers, into their new repository, but not the actual large files. The large files are stored in the LFS server of [our repository](https://github.com/gentzkow/GentzkowLabTemplate) and are not automatically transferred to the user's repository’s LFS server, so the user must set up Git LFS in their new repository and download the large files. After running `git lfs install`, they should also run `git lfs pull` in the local directory that they have cloned:
    - A) Directly from the original [GentzkowLabTemplate](https://github.com/gentzkow/GentzkowLabTemplate)
    - B) And NOT from their own username/GentzkowLabTemplate that is cloned from the original [GentzkowLabTemplate](https://github.com/gentzkow/GentzkowLabTemplate)
        - This will return error `[404] Object does not exist on the server`

    If A) is done correctly, they can then push the metadata (pointer files) to their own Git repository (`git push origin main`) and the large file data to their LFS server (`git lfs push --all origin`).

    Currently there is another minor problem preventing this procedure. `git clone git@github.com:gentzkow/GentzkowLabTemplate.git` would return this message: 

    > Encountered 1 file that should have been a pointer, but wasn't: examples/powerpoint/output/slides.pdf

    I did some checks and found that when Matt committed `slides.pdf` on Aug 2, it was not committed as a Git LFS pointer file but as a full binary file. Since the `.gitattributes` file specifies that .pdf files are tracked by Git LFS, this file was likely added before Git LFS was set up or before the `.gitattributes` was configured properly. So we could consider keep using Git LFS if we fix this minor issue and write detailed guidelines in [README.md](https://github.com/gentzkow/GentzkowLabTemplate/blob/6c534efcaa2d5bd9a65e06c7822a670ff1a34da1/README.md).

@ShiqiYang2022 @lucamlouzada

**Comment by lucamlouzada** [comment]
Nice @linxicindyzeng ! I had seen these messages about the pointer, but did not investigate further. Thanks for the great explanation. We can discuss these alternatives in the meeting tomorrow, though I suspect using regular git for these files will be a simpler approach as it requires no extra steps from the users running the examples - and does not prevent the remaining parts of the template from using Git LFS if needed.
cc @ShiqiYang2022

**Comment by linxicindyzeng** [comment]
@lucamlouzada I agree. If the purpose of using Git LFS in the template is just to demonstrate two .jpg's and one .csv, we should get rid of LFS and use normal git. If we want to make room for future adjustments in the template where LFS may become essential, we should keep it.

**Comment by gentzkow** [comment]
Hi all: Chiming in here on the LFS issue, I agree w/ this conclusion. We've actually known about this issue in the past and I just forgot about it when I was adding LFS to the template. 

What we need to achieve, ideally, is:

1. The template can run out of the box without Git LFS installed and it functions correctly as a template on Github.

2. The template is preconfigured so that someone who *does* want to use LFS can do so easily.

3. We have good ways of enforcing that all of our lab projects *must* be using LFS.

One possibility for (2) would be that we can make LFS an extension in `/examples/` -- the directory would just need to have a readme explaining the steps and our default `.gitattributes`.

**Comment by linxicindyzeng** [comment]
@gentzkow I agree. Making it an available but not necessary extension is a great idea. Using normal Git for example inputs should solve 1. For 3., since we are not structurally forcing the usage of LFS due to 1., we can ensure this elsewhere (e.g., in a manual or README). If we want to have the choice of structurally ensuring the usage of LFS (such that not using it would cause errors), we can also code it up and include this check in the extension folder?

**Comment by linxicindyzeng** [comment]
2. `bash run_all.sh` and `bash run_latex.sh` no longer report errors after Luca's three commits in branch [15-familiarize](https://github.com/gentzkow/GentzkowLabTemplate/tree/15-familiarize).

**Comment by lucamlouzada** [comment]
Hi @linxicindyzeng, I just wanted to confirm whether you have any other suggestions to add to this branch or if we can wrap up this issue and commit my three changes to main. Thanks!

**Comment by linxicindyzeng** [comment]
I don’t have other suggestions :) thanks!

**Comment by ShiqiYang2022** [comment]
Threads continues in its PR #17.

**Comment by lucamlouzada** [comment]
**Summary**: 
In this issue we noted some minor improvements to the new lab template. Some changes were applied in the associated PR #17.

The changes were:

- In https://github.com/gentzkow/GentzkowLabTemplate/commit/214714de67b4ebcb3c75b8e763e8649fbf3b188e, I changed the example slides .tex file to use the [moloch ](https://github.com/jolars/moloch)theme instead of the metropolis theme.
- In https://github.com/gentzkow/GentzkowLabTemplate/commit/cfeb9c2440c01e4415a65a5f139b2a0a69750952, I changed the lib/shell/run_latex file to ensure the cleanup part is always run
- In https://github.com/gentzkow/GentzkowLabTemplate/commit/6e793d89a5dcc6f3b1f75ab7ea1d2881cfaca8a0, I fixed the examples/latex/README.md file so the wildcard is properly used in the sample lines of code. There was a minor issue with my fix which was handled in [dd6e30a](https://github.com/gentzkow/GentzkowLabTemplate/commit/dd6e30ae46d0e95f49d265dbef98806193566347) following a review by @ShiqiYang2022 .

 **Deliverables:**
- [examples/latex/my_project_slides.tex](https://github.com/gentzkow/GentzkowLabTemplate/blob/6e793d89a5dcc6f3b1f75ab7ea1d2881cfaca8a0/examples/latex/my_project_slides.tex)
- [examples/latex/README.md](https://github.com/gentzkow/GentzkowLabTemplate/blob/dd6e30ae46d0e95f49d265dbef98806193566347/examples/latex/README.md)
- [lib/shell/run_latex.sh](https://github.com/gentzkow/GentzkowLabTemplate/blob/6e793d89a5dcc6f3b1f75ab7ea1d2881cfaca8a0/lib/shell/run_latex.sh)
